import type { RatingDefinition } from "./types";

/**
 * A rating dimension available to pick from, grouped by category and with a
 * plain-language note on what it actually measures.
 */
export interface LibraryRating extends RatingDefinition {
  category: string;
  description: string;
  scale: string[];
}

/**
 * The shared catalogue of rating dimensions. Exercises seed their defaults
 * from here and sessions can pull in any of them, so wording stays
 * consistent across every session rather than being re-invented each time.
 */
export const RATING_LIBRARY: LibraryRating[] = [
  {
    category: "Control",
    key: "body_stability",
    label: "Body Stability",
    description: "How steady the body stays through the movement or hold",
    max: 5,
    scale: [
      "Wobbling or repositioning constantly",
      "Frequently unsteady",
      "Holds with visible effort",
      "Steady with minor adjustment",
      "Completely steady throughout",
    ],
  },
  {
    category: "Forelimb",
    key: "forelimb_control",
    label: "Forelimb Control",
    description: "Deliberate, even use of the front limbs",
    max: 5,
    scale: [
      "Little control; propping or collapsing",
      "Frequently uneven or braced",
      "Moderate control",
      "Mostly even and deliberate",
      "Fully controlled and even",
    ],
  },
  {
    category: "Load",
    key: "intensity",
    label: "Intensity",
    description: "Overall physical effort of the exercise",
    max: 5,
    scale: [
      "Very light; minimal effort",
      "Light effort",
      "Moderate effort",
      "High effort",
      "Very high / near-max effort",
    ],
  },
  {
    category: "Conditioning",
    key: "endurance",
    label: "Endurance",
    description: "Ability to sustain the required work",
    max: 5,
    scale: [
      "Fatigues very quickly",
      "Limited duration; frequent breaks",
      "Completes moderate work",
      "Sustains work well",
      "Sustains prolonged work with little deterioration",
    ],
  },
  {
    category: "Conditioning",
    key: "muscular_endurance",
    label: "Muscular Endurance",
    description: "Ability of muscles to repeatedly produce useful work",
    max: 5,
    scale: [
      "Rapid muscular fatigue",
      "Early decline in output",
      "Moderate sustained output",
      "Strong sustained output",
      "Excellent repeated output with minimal decline",
    ],
  },
  {
    category: "Conditioning",
    key: "pace_consistency",
    label: "Pace Consistency",
    description: "Ability to maintain a stable working pace",
    max: 5,
    scale: [
      "Highly inconsistent",
      "Frequent pace changes",
      "Mostly consistent",
      "Very consistent",
      "Extremely steady throughout",
    ],
  },
  {
    category: "Conditioning",
    key: "fatigue_resistance",
    label: "Fatigue Resistance",
    description: "Ability to maintain overall performance as fatigue accumulates",
    max: 5,
    scale: [
      "Rapid deterioration",
      "Clear deterioration",
      "Mild-moderate deterioration",
      "Small deterioration",
      "No meaningful deterioration",
    ],
  },
  {
    category: "Conditioning",
    key: "form_under_fatigue",
    label: "Form Under Fatigue",
    description: "Ability to preserve movement mechanics when tired",
    max: 5,
    scale: [
      "Major breakdown",
      "Clear form deterioration",
      "Noticeable but manageable change",
      "Minor form change",
      "Form remains essentially unchanged",
    ],
  },
  {
    category: "Conditioning",
    key: "recovery",
    label: "Recovery",
    description: "Ability to return toward baseline after exercise",
    max: 5,
    scale: [
      "Very slow recovery",
      "Slow recovery",
      "Moderate recovery",
      "Quick recovery",
      "Very rapid / excellent recovery",
    ],
  },
  {
    category: "Conditioning",
    key: "breathing_recovery",
    label: "Breathing Recovery",
    description: "How quickly respiratory effort settles after exercise",
    max: 5,
    scale: [
      "Remains heavily elevated",
      "Slow reduction",
      "Gradual recovery",
      "Rapid recovery",
      "Returns near baseline very quickly",
    ],
  },
  {
    category: "Movement",
    key: "gait_form",
    label: "Gait / Form",
    description: "Overall quality of movement mechanics",
    max: 5,
    scale: [
      "Poor / clearly compromised",
      "Multiple visible issues",
      "Functional but imperfect",
      "Good movement quality",
      "Excellent, clean movement",
    ],
  },
  {
    category: "Movement",
    key: "symmetry",
    label: "Symmetry",
    description: "Similarity of movement/loading between left and right",
    max: 5,
    scale: [
      "Clear persistent asymmetry",
      "Moderate asymmetry",
      "Mild/inconsistent asymmetry",
      "Nearly symmetrical",
      "Highly symmetrical",
    ],
  },
  {
    category: "Movement",
    key: "coordination",
    label: "Coordination",
    description: "Timing and sequencing between limbs/body",
    max: 5,
    scale: [
      "Poorly coordinated",
      "Frequent timing errors",
      "Functional coordination",
      "Smooth coordination",
      "Highly fluid and precise",
    ],
  },
  {
    category: "Movement",
    key: "balance_stability",
    label: "Balance / Stability",
    description: "Ability to remain stable while moving or holding position",
    max: 5,
    scale: [
      "Frequently loses stability",
      "Noticeably unstable",
      "Generally stable",
      "Very stable",
      "Exceptional stability and control",
    ],
  },
  {
    category: "Movement",
    key: "postural_control",
    label: "Postural Control",
    description: "Ability to maintain intended body alignment",
    max: 5,
    scale: [
      "Poor alignment",
      "Frequent loss of posture",
      "Acceptable posture",
      "Good posture",
      "Excellent consistent alignment",
    ],
  },
  {
    category: "Movement",
    key: "trunk_core_stability",
    label: "Trunk / Core Stability",
    description: "Control of torso during movement",
    max: 5,
    scale: [
      "Significant trunk movement/collapse",
      "Limited trunk control",
      "Moderate stability",
      "Strong stability",
      "Excellent trunk control",
    ],
  },
  {
    category: "Movement",
    key: "paw_placement",
    label: "Paw Placement",
    description: "Accuracy and consistency of where paws land",
    max: 5,
    scale: [
      "Very inaccurate",
      "Frequent placement errors",
      "Generally appropriate",
      "Accurate placement",
      "Highly precise and repeatable",
    ],
  },
  {
    category: "Movement",
    key: "stride_consistency",
    label: "Stride Consistency",
    description: "Repeatability of successive strides",
    max: 5,
    scale: [
      "Highly variable",
      "Noticeably inconsistent",
      "Mostly consistent",
      "Consistent",
      "Extremely repeatable",
    ],
  },
  {
    category: "Movement",
    key: "stride_quality",
    label: "Stride Quality",
    description: "Quality of reach, stance and push-through",
    max: 5,
    scale: [
      "Poor / restricted",
      "Limited",
      "Functional",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Movement",
    key: "limb_clearance",
    label: "Limb Clearance",
    description: "Ability to lift limbs sufficiently during swing",
    max: 5,
    scale: [
      "Frequent contact/dragging",
      "Occasional clearance issues",
      "Adequate clearance",
      "Good clearance",
      "Consistently clean clearance",
    ],
  },
  {
    category: "Movement",
    key: "range_of_motion",
    label: "Range of Motion",
    description: "Functional movement excursion during exercise",
    max: 5,
    scale: [
      "Very restricted",
      "Restricted",
      "Adequate",
      "Good",
      "Full, controlled functional range",
    ],
  },
  {
    category: "Movement",
    key: "movement_fluidity",
    label: "Movement Fluidity",
    description: "Smoothness of transitions through each movement",
    max: 5,
    scale: [
      "Jerky / interrupted",
      "Frequently hesitant",
      "Generally smooth",
      "Smooth",
      "Very fluid and effortless",
    ],
  },
  {
    category: "Movement",
    key: "directional_control",
    label: "Directional Control",
    description: "Ability to maintain intended direction/path",
    max: 5,
    scale: [
      "Poor control",
      "Frequent deviation",
      "Generally maintains path",
      "Good directional control",
      "Very precise",
    ],
  },
  {
    category: "Movement",
    key: "turn_quality",
    label: "Turn Quality",
    description: "Balance/control when changing direction",
    max: 5,
    scale: [
      "Poor, unstable turns",
      "Awkward or inconsistent",
      "Functional",
      "Smooth",
      "Controlled, balanced and fluid",
    ],
  },
  {
    category: "Hind Limb",
    key: "hind_limb_engagement",
    label: "Hind Limb Engagement",
    description: "Degree to which rear limbs actively contribute",
    max: 5,
    scale: [
      "Minimal contribution",
      "Limited contribution",
      "Moderate engagement",
      "Strong engagement",
      "Powerful, consistent engagement",
    ],
  },
  {
    category: "Hind Limb",
    key: "hind_limb_symmetry",
    label: "Hind Limb Symmetry",
    description: "Equality of left/right rear-limb contribution",
    max: 5,
    scale: [
      "Clear persistent difference",
      "Moderate difference",
      "Mild/inconsistent difference",
      "Nearly equal",
      "Highly symmetrical",
    ],
  },
  {
    category: "Hind Limb",
    key: "rear_propulsion",
    label: "Rear Propulsion",
    description: "Strength and effectiveness of rear push-off",
    max: 5,
    scale: [
      "Minimal propulsion",
      "Weak push",
      "Functional propulsion",
      "Strong push",
      "Powerful, efficient propulsion",
    ],
  },
  {
    category: "Hind Limb",
    key: "hip_extension",
    label: "Hip Extension",
    description: "Quality of extension through the hip during push-off",
    max: 5,
    scale: [
      "Very limited",
      "Limited",
      "Moderate",
      "Good",
      "Strong/full functional extension",
    ],
  },
  {
    category: "Hind Limb",
    key: "hock_control",
    label: "Hock Control",
    description: "Stability/alignment through the hock",
    max: 5,
    scale: [
      "Poor control",
      "Frequent instability",
      "Functional",
      "Good control",
      "Excellent stability",
    ],
  },
  {
    category: "Hind Limb",
    key: "rear_paw_tracking",
    label: "Rear Paw Tracking",
    description: "Consistency and alignment of rear paw movement",
    max: 5,
    scale: [
      "Highly irregular",
      "Frequently inconsistent",
      "Generally appropriate",
      "Consistent",
      "Precise and repeatable",
    ],
  },
  {
    category: "Forelimb",
    key: "forelimb_tracking",
    label: "Forelimb Tracking",
    description: "Straightness and consistency of forelimb path",
    max: 5,
    scale: [
      "Major deviation",
      "Repeated deviation",
      "Mild/inconsistent deviation",
      "Mostly straight",
      "Clean, consistent tracking",
    ],
  },
  {
    category: "Forelimb",
    key: "forelimb_symmetry",
    label: "Forelimb Symmetry",
    description: "Equality of left/right front-limb movement",
    max: 5,
    scale: [
      "Clear asymmetry",
      "Moderate asymmetry",
      "Mild difference",
      "Nearly equal",
      "Highly symmetrical",
    ],
  },
  {
    category: "Forelimb",
    key: "shoulder_control",
    label: "Shoulder Control",
    description: "Stability and controlled movement around shoulder",
    max: 5,
    scale: [
      "Poor",
      "Limited",
      "Functional",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Strength",
    key: "strength",
    label: "Strength",
    description: "Ability to generate controlled force",
    max: 5,
    scale: [
      "Very limited",
      "Below required level",
      "Adequate",
      "Strong",
      "Very strong",
    ],
  },
  {
    category: "Strength",
    key: "power",
    label: "Power",
    description: "Ability to generate force quickly",
    max: 5,
    scale: [
      "Minimal explosive output",
      "Limited",
      "Moderate",
      "Strong",
      "Highly powerful",
    ],
  },
  {
    category: "Strength",
    key: "push_strength",
    label: "Push Strength",
    description: "Ability to drive body forward/up/back against resistance",
    max: 5,
    scale: [
      "Weak",
      "Limited",
      "Adequate",
      "Strong",
      "Very strong",
    ],
  },
  {
    category: "Strength",
    key: "weight_bearing_control",
    label: "Weight-Bearing Control",
    description: "Ability to accept and control load through limbs",
    max: 5,
    scale: [
      "Poor",
      "Limited",
      "Adequate",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Strength",
    key: "weight_shift",
    label: "Weight Shift",
    description: "Ability to deliberately transfer load",
    max: 5,
    scale: [
      "Poor / avoids shift",
      "Limited control",
      "Functional",
      "Good",
      "Precise and controlled",
    ],
  },
  {
    category: "Control",
    key: "movement_control",
    label: "Movement Control",
    description: "Ability to perform slowly and deliberately",
    max: 5,
    scale: [
      "Little control",
      "Frequently rushed",
      "Moderate control",
      "Controlled",
      "Highly deliberate and precise",
    ],
  },
  {
    category: "Control",
    key: "tempo_control",
    label: "Tempo Control",
    description: "Ability to maintain requested movement tempo",
    max: 5,
    scale: [
      "Cannot maintain",
      "Frequently changes",
      "Mostly maintains",
      "Consistent",
      "Precise throughout",
    ],
  },
  {
    category: "Control",
    key: "position_control",
    label: "Position Control",
    description: "Ability to achieve and maintain requested position",
    max: 5,
    scale: [
      "Poor",
      "Frequent corrections",
      "Functional",
      "Good",
      "Precise and stable",
    ],
  },
  {
    category: "Control",
    key: "transition_quality",
    label: "Transition Quality",
    description: "Quality moving between positions/movements",
    max: 5,
    scale: [
      "Poor / unstable",
      "Awkward",
      "Functional",
      "Smooth",
      "Seamless and controlled",
    ],
  },
  {
    category: "Control",
    key: "technical_accuracy",
    label: "Technical Accuracy",
    description: "How correctly the exercise is performed",
    max: 5,
    scale: [
      "Incorrect",
      "Significant errors",
      "Generally correct",
      "Very good",
      "Precise execution",
    ],
  },
  {
    category: "Obstacle Work",
    key: "obstacle_clearance",
    label: "Obstacle Clearance",
    description: "Ability to clear poles/objects without contact",
    max: 5,
    scale: [
      "Frequent contact",
      "Multiple contacts",
      "Occasional contact",
      "Rare contact",
      "Clean every time",
    ],
  },
  {
    category: "Obstacle Work",
    key: "foot_placement_accuracy",
    label: "Foot Placement Accuracy",
    description: "Paw placement relative to obstacles/targets",
    max: 5,
    scale: [
      "Very inaccurate",
      "Frequent errors",
      "Mostly appropriate",
      "Accurate",
      "Highly precise",
    ],
  },
  {
    category: "Obstacle Work",
    key: "obstacle_rhythm",
    label: "Obstacle Rhythm",
    description: "Ability to maintain rhythm through repeated obstacles",
    max: 5,
    scale: [
      "No stable rhythm",
      "Frequently disrupted",
      "Functional rhythm",
      "Consistent rhythm",
      "Smooth, uninterrupted rhythm",
    ],
  },
  {
    category: "Obstacle Work",
    key: "obstacle_awareness",
    label: "Obstacle Awareness",
    description: "Apparent awareness and adjustment to obstacle position",
    max: 5,
    scale: [
      "Poor",
      "Limited",
      "Adequate",
      "Good",
      "Excellent proactive adjustment",
    ],
  },
  {
    category: "Cardio",
    key: "working_pace",
    label: "Working Pace",
    description: "Quality/appropriateness of pace for prescribed exercise",
    max: 5,
    scale: [
      "Unable to maintain target",
      "Frequently outside target",
      "Generally appropriate",
      "Good target pace",
      "Precise, effortless target pace",
    ],
  },
  {
    category: "Cardio",
    key: "speed_control",
    label: "Speed Control",
    description: "Ability to maintain intended speed without rushing/lagging",
    max: 5,
    scale: [
      "Poor",
      "Inconsistent",
      "Adequate",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Cardio",
    key: "incline_technique",
    label: "Incline Technique",
    description: "Mechanics while working against an incline",
    max: 5,
    scale: [
      "Major compensation",
      "Clear compensation",
      "Functional",
      "Good",
      "Excellent efficient incline mechanics",
    ],
  },
  {
    category: "Cardio",
    key: "efficiency",
    label: "Efficiency",
    description: "Amount of unnecessary movement/effort",
    max: 5,
    scale: [
      "Highly inefficient",
      "Noticeably inefficient",
      "Functional",
      "Efficient",
      "Very efficient",
    ],
  },
  {
    category: "Mobility",
    key: "mobility",
    label: "Mobility",
    description: "Ability to move through required functional ranges",
    max: 5,
    scale: [
      "Very restricted",
      "Restricted",
      "Adequate",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Mobility",
    key: "flexibility_range",
    label: "Flexibility / Range",
    description: "Available range required by the task",
    max: 5,
    scale: [
      "Very limited",
      "Limited",
      "Moderate",
      "Good",
      "Full functional range",
    ],
  },
  {
    category: "Mobility",
    key: "dynamic_mobility",
    label: "Dynamic Mobility",
    description: "Range while actively moving rather than passively",
    max: 5,
    scale: [
      "Very restricted",
      "Restricted",
      "Functional",
      "Good",
      "Excellent active range",
    ],
  },
  {
    category: "Mobility",
    key: "rotation",
    label: "Rotation",
    description: "Ability to rotate trunk/neck/body as required",
    max: 5,
    scale: [
      "Very restricted",
      "Restricted",
      "Functional",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Mobility",
    key: "extension",
    label: "Extension",
    description: "Ability to achieve controlled extension",
    max: 5,
    scale: [
      "Very limited",
      "Limited",
      "Functional",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Mobility",
    key: "flexion",
    label: "Flexion",
    description: "Ability to achieve controlled flexion",
    max: 5,
    scale: [
      "Very limited",
      "Limited",
      "Functional",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Proprioception",
    key: "body_awareness",
    label: "Body Awareness",
    description: "Awareness/control of limb and body positioning",
    max: 5,
    scale: [
      "Poor",
      "Limited",
      "Developing",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Proprioception",
    key: "rear_end_awareness",
    label: "Rear-End Awareness",
    description: "Intentional control of hindquarters",
    max: 5,
    scale: [
      "Minimal awareness",
      "Limited",
      "Moderate",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Proprioception",
    key: "paw_awareness",
    label: "Paw Awareness",
    description: "Intentional awareness/control of individual paw placement",
    max: 5,
    scale: [
      "Poor",
      "Limited",
      "Developing",
      "Good",
      "Highly precise",
    ],
  },
  {
    category: "Proprioception",
    key: "surface_adaptation",
    label: "Surface Adaptation",
    description: "Ability to adapt movement to changing/unstable surfaces",
    max: 5,
    scale: [
      "Poor",
      "Hesitant/unstable",
      "Functional",
      "Good",
      "Confident and highly adaptive",
    ],
  },
  {
    category: "Behavior",
    key: "focus",
    label: "Focus",
    description: "Attention to task",
    max: 5,
    scale: [
      "Highly distracted",
      "Frequently distracted",
      "Moderately focused",
      "Strong focus",
      "Fully engaged throughout",
    ],
  },
  {
    category: "Behavior",
    key: "engagement",
    label: "Engagement",
    description: "Willing participation in exercise",
    max: 5,
    scale: [
      "Reluctant",
      "Low engagement",
      "Cooperative",
      "Highly engaged",
      "Enthusiastic and consistently engaged",
    ],
  },
  {
    category: "Behavior",
    key: "motivation",
    label: "Motivation",
    description: "Drive/willingness to continue working",
    max: 5,
    scale: [
      "Very low",
      "Low",
      "Moderate",
      "High",
      "Very high",
    ],
  },
  {
    category: "Behavior",
    key: "confidence",
    label: "Confidence",
    description: "Confidence performing the task",
    max: 5,
    scale: [
      "Highly hesitant",
      "Hesitant",
      "Neutral/functional",
      "Confident",
      "Very confident",
    ],
  },
  {
    category: "Behavior",
    key: "responsiveness",
    label: "Responsiveness",
    description: "Response to handler cues",
    max: 5,
    scale: [
      "Rare/inconsistent response",
      "Slow/frequent repetition",
      "Generally responsive",
      "Quick response",
      "Immediate, reliable response",
    ],
  },
  {
    category: "Behavior",
    key: "arousal_control",
    label: "Arousal Control",
    description: "Ability to remain appropriately regulated",
    max: 5,
    scale: [
      "Highly over/under-aroused",
      "Frequently dysregulated",
      "Mostly manageable",
      "Well regulated",
      "Ideal calm working state",
    ],
  },
  {
    category: "Behavior",
    key: "independence",
    label: "Independence",
    description: "Ability to perform without continuous lure/support",
    max: 5,
    scale: [
      "Requires continuous help",
      "Significant assistance",
      "Moderate assistance",
      "Minimal assistance",
      "Performs independently",
    ],
  },
  {
    category: "Behavior",
    key: "task_understanding",
    label: "Task Understanding",
    description: "Apparent understanding of exercise requirements",
    max: 5,
    scale: [
      "Little understanding",
      "Inconsistent",
      "Understands basics",
      "Strong understanding",
      "Clear mastery",
    ],
  },
  {
    category: "Behavior",
    key: "consistency",
    label: "Consistency",
    description: "Repeatability across repetitions",
    max: 5,
    scale: [
      "Highly variable",
      "Variable",
      "Mostly consistent",
      "Very consistent",
      "Virtually identical execution",
    ],
  },
  {
    category: "Quality",
    key: "overall_performance",
    label: "Overall Performance",
    description: "Holistic assessment of the exercise",
    max: 5,
    scale: [
      "Poor",
      "Below expected",
      "Acceptable",
      "Good",
      "Excellent",
    ],
  },
  {
    category: "Quality",
    key: "exercise_quality",
    label: "Exercise Quality",
    description: "Overall quality relative to intended exercise goal",
    max: 5,
    scale: [
      "Very poor",
      "Limited",
      "Functional",
      "Strong",
      "Excellent",
    ],
  },
  {
    category: "Quality",
    key: "progression_readiness",
    label: "Progression Readiness",
    description: "Whether current performance supports increasing challenge",
    max: 5,
    scale: [
      "Not ready",
      "Needs substantial improvement",
      "Nearly ready",
      "Ready for small progression",
      "Clearly ready to progress",
    ],
  },
];

/** Category names in the order they should appear in a picker. */
export const RATING_CATEGORIES: string[] = Array.from(
  new Set(RATING_LIBRARY.map((r) => r.category)),
);

/** Case-insensitive match across label, category and description. */
export function searchRatingLibrary(query: string): LibraryRating[] {
  const q = query.trim().toLowerCase();
  if (!q) return RATING_LIBRARY;
  return RATING_LIBRARY.filter((r) =>
    `${r.label} ${r.category} ${r.description}`.toLowerCase().includes(q),
  );
}
