/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    dogs: Dog;
    plans: Plan;
    'rating-dimensions': RatingDimension;
    exercises: Exercise;
    sessions: Session;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    dogs: DogsSelect<false> | DogsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'rating-dimensions': RatingDimensionsSelect<false> | RatingDimensionsSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name; falls back to the email address.
   */
  name?: string | null;
  /**
   * Drives which navigation and screens this person sees. It does not yet restrict what the API returns — that is a separate access change.
   */
  role?: ('owner' | 'trainer' | 'admin') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogs".
 */
export interface Dog {
  id: number;
  name: string;
  /**
   * Profile photo shown in the dog selector and header.
   */
  photo?: (number | null) | Media;
  breed?: string | null;
  /**
   * Used to show the dog's age; no age is shown without it.
   */
  dateOfBirth?: string | null;
  sex?: ('male' | 'female') | null;
  /**
   * Current weight in kilograms.
   */
  weightKg?: number | null;
  /**
   * What the current programme is working on, e.g. "Hind-limb strength after CCL repair".
   */
  trainingFocus?: string | null;
  /**
   * Short goal statements, one per entry.
   */
  trainingGoals?: string[] | null;
  /**
   * Standing observations about how this dog moves, carried across sessions.
   */
  movementObservations?: string | null;
  /**
   * Things to avoid, e.g. "No jumping above hock height". Shown on the dog profile.
   */
  restrictions?: string[] | null;
  notes?: string | null;
  /**
   * Recorded for a later access change; not enforced yet.
   */
  owners?: (number | User)[] | null;
  /**
   * Recorded for a later access change; not enforced yet.
   */
  trainers?: (number | User)[] | null;
  /**
   * Archived dogs stay in the record but drop out of the dog selector.
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  dog: number | Dog;
  /**
   * The plan the calendar shows. Keep one active per dog; older ones stay for the record.
   */
  active?: boolean | null;
  notes?: string | null;
  /**
   * One entry per planned activity. Several can share a day and category — the calendar stacks them in that cell.
   */
  items?:
    | {
        /**
         * 0 = Sunday, 6 = Saturday.
         */
        dayOfWeek: number;
        category: 'cardio' | 'strength' | 'flexibility' | 'bodyAwareness' | 'enrichment' | 'sport';
        title: string;
        /**
         * How to run it. Line breaks are kept.
         */
        detail?: string | null;
        /**
         * Planned minutes. Set both for a range like 45-60.
         */
        durationMinMinutes?: number | null;
        durationMaxMinutes?: number | null;
        intensity: 'low' | 'lowModerate' | 'moderate' | 'moderateHigh' | 'rest';
        /**
         * Do it if the day allows; not counted as missed.
         */
        optional?: boolean | null;
        /**
         * When to stop or skip, e.g. "Stop if gait changes". Shown on its own so it is not lost in the instructions.
         */
        stopRule?: string | null;
        /**
         * Swaps for this slot — any one of them counts.
         */
        alternatives?:
          | {
              title: string;
              detail?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Links the plan to the exercise library. Without it the calendar can't tell whether this was done — a logged session is matched to a plan item by day and exercise.
         */
        exercise?: (number | null) | Exercise;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  id: number;
  name: string;
  /**
   * The type of exercise, not the body part — that is what Focus is for.
   */
  category:
    | 'Walking & General Activity'
    | 'Conditioning'
    | 'Strength'
    | 'Coordination & Proprioception'
    | 'Mobility'
    | 'Speed & Power'
    | 'Recovery / Low Impact';
  /**
   * What it trains. Suggested values: General, Cardio, Conditioning, Muscular Endurance, Strength, Power, Hind Limb, Forelimb, Core, Spine, Neck, Mobility, Balance, Stability, Coordination, Proprioception, Body Awareness, Paw Awareness, Movement Control, Directional Control, Gait, Recovery, Low Impact. Custom values are allowed.
   */
  focus?: string[] | null;
  /**
   * What the exercise involves and why it is done.
   */
  description?: string | null;
  /**
   * Decides which fields the session form offers for this exercise.
   */
  trackingMethods?:
    | (
        | 'Duration'
        | 'Active Duration'
        | 'Distance'
        | 'Reps'
        | 'Reps per Side'
        | 'Sets'
        | 'Passes'
        | 'Intervals'
        | 'Hold Time'
        | 'Steps'
      )[]
    | null;
  /**
   * Default unit for the primary tracking method.
   */
  primaryUnit?:
    | ('Seconds' | 'Minutes' | 'Hours' | 'Meters' | 'Kilometers' | 'Miles' | 'Reps' | 'Passes' | 'Steps' | 'Intervals')
    | null;
  /**
   * Normally required. Suggested values: None, Treadmill, Carpetmill, Slatmill, Underwater Treadmill, Pool, Cavaletti Poles, Platform, Step, Balance Pad, Cones, Target. Custom values are allowed.
   */
  equipment?: string[] | null;
  /**
   * What good execution and setup look like.
   */
  techniqueNotes?: string | null;
  /**
   * Presented when logging this exercise, in this order. References the global Rating Library rather than copying it; removing one here leaves the dimension itself alone.
   */
  defaultRatingDimensions?: (number | RatingDimension)[] | null;
  /**
   * Archived exercises drop out of new-session selection but keep every session that referenced them.
   */
  status: 'active' | 'archived';
  /**
   * Superseded by defaultRatingDimensions. Kept so exercises defined before the Rating Library became a collection aren't lost; the seed migrates them across.
   */
  defaultRatings?:
    | {
        key: string;
        label: string;
        max: number;
        scale?: string[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rating-dimensions".
 */
export interface RatingDimension {
  id: number;
  /**
   * Stable identifier; scores are stored against it.
   */
  key: string;
  label: string;
  /**
   * Grouping in the picker, e.g. Movement, Strength.
   */
  category?: string | null;
  /**
   * What this dimension is judging.
   */
  description?: string | null;
  /**
   * Top of the scale. 5 throughout the seeded library.
   */
  max: number;
  /**
   * The 1-5 descriptors, worst to best. For a workload dimension such as Intensity, 5 is the heaviest workload rather than the best performance.
   */
  scale?: string[] | null;
  /**
   * Hidden from the picker; existing uses are untouched.
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  /**
   * Which dog performed this session.
   */
  dog?: (number | null) | Dog;
  exercise: number | Exercise;
  date: string;
  /**
   * One entry per set performed, holding that set's work, scores and notes. Rating labels/max/scale come from the exercise's own dimensions, not stored here.
   */
  sets?:
    | {
        setNumber: number;
        reps?: number | null;
        /**
         * For exercises tracked per side.
         */
        repsLeft?: number | null;
        repsRight?: number | null;
        /**
         * Elapsed time for this set, in seconds.
         */
        durationSeconds?: number | null;
        /**
         * Time actually moving — belt time, swim time — as opposed to elapsed.
         */
        activeDurationSeconds?: number | null;
        /**
         * Stored in metres whatever unit is displayed.
         */
        distanceMeters?: number | null;
        intervals?: number | null;
        /**
         * For static holds.
         */
        holdSeconds?: number | null;
        steps?: number | null;
        /**
         * For exercises counted in passes rather than reps (e.g. cavaletti).
         */
        passes?: number | null;
        /**
         * Note about this set specifically.
         */
        notes?: string | null;
        /**
         * Superseded by watchPoints, which can carry a timestamp. Kept so sessions saved before that aren't lost; the seed copies them across and the app writes only watchPoints.
         */
        watchItems?: string[] | null;
        /**
         * Short things to watch for in this set, e.g. "left knee flaring", each optionally pinned to a moment in that set's video.
         */
        watchPoints?:
          | {
              text: string;
              /**
               * Where in the set's clip this shows, in seconds. Empty when it isn't tied to a moment.
               */
              atSeconds?: number | null;
              id?: string | null;
            }[]
          | null;
        ratings?:
          | {
              key: string;
              score: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * This session's rating dimensions, seeded from the exercise as a template then editable here.
   */
  ratingDefs?:
    | {
        key: string;
        label: string;
        max: number;
        scale?: string[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Rest taken between sets.
   */
  restLabel?: string | null;
  /**
   * Where the session took place; used to look up the weather.
   */
  locationName?: string | null;
  /**
   * Decimal degrees.
   */
  latitude?: number | null;
  /**
   * Decimal degrees.
   */
  longitude?: number | null;
  /**
   * Conditions at the session's time and place, fetched once and stored so the record doesn't change later.
   */
  weather?: {
    temperatureC?: number | null;
    humidityPercent?: number | null;
    description?: string | null;
    fetchedAt?: string | null;
  };
  /**
   * Where and under what conditions, e.g. "Outside — warm" or "Air-conditioned gym".
   */
  environment?: string | null;
  notes?: string | null;
  /**
   * Videos/photos belonging to this session, in order. Each one belongs to a specific set.
   */
  media?:
    | {
        /**
         * Which set this clip/photo was taken during.
         */
        setNumber: number;
        type: 'video' | 'image';
        file: number | Media;
        label?: string | null;
        /**
         * What to look for in this clip. Line breaks are kept and shown on the feed.
         */
        notes?: string | null;
        duration?: string | null;
        /**
         * Seconds of actual movement, prepopulated from the clip's duration then editable.
         */
        activeMovementSeconds?: number | null;
        /**
         * When the clip/photo was recorded, read from the file's own metadata on upload.
         */
        capturedAt?: string | null;
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'dogs';
        value: number | Dog;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'rating-dimensions';
        value: number | RatingDimension;
      } | null)
    | ({
        relationTo: 'exercises';
        value: number | Exercise;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogs_select".
 */
export interface DogsSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  breed?: T;
  dateOfBirth?: T;
  sex?: T;
  weightKg?: T;
  trainingFocus?: T;
  trainingGoals?: T;
  movementObservations?: T;
  restrictions?: T;
  notes?: T;
  owners?: T;
  trainers?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  dog?: T;
  active?: T;
  notes?: T;
  items?:
    | T
    | {
        dayOfWeek?: T;
        category?: T;
        title?: T;
        detail?: T;
        durationMinMinutes?: T;
        durationMaxMinutes?: T;
        intensity?: T;
        optional?: T;
        stopRule?: T;
        alternatives?:
          | T
          | {
              title?: T;
              detail?: T;
              id?: T;
            };
        exercise?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rating-dimensions_select".
 */
export interface RatingDimensionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  category?: T;
  description?: T;
  max?: T;
  scale?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  focus?: T;
  description?: T;
  trackingMethods?: T;
  primaryUnit?: T;
  equipment?: T;
  techniqueNotes?: T;
  defaultRatingDimensions?: T;
  status?: T;
  defaultRatings?:
    | T
    | {
        key?: T;
        label?: T;
        max?: T;
        scale?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  dog?: T;
  exercise?: T;
  date?: T;
  sets?:
    | T
    | {
        setNumber?: T;
        reps?: T;
        repsLeft?: T;
        repsRight?: T;
        durationSeconds?: T;
        activeDurationSeconds?: T;
        distanceMeters?: T;
        intervals?: T;
        holdSeconds?: T;
        steps?: T;
        passes?: T;
        notes?: T;
        watchItems?: T;
        watchPoints?:
          | T
          | {
              text?: T;
              atSeconds?: T;
              id?: T;
            };
        ratings?:
          | T
          | {
              key?: T;
              score?: T;
              id?: T;
            };
        id?: T;
      };
  ratingDefs?:
    | T
    | {
        key?: T;
        label?: T;
        max?: T;
        scale?: T;
        id?: T;
      };
  restLabel?: T;
  locationName?: T;
  latitude?: T;
  longitude?: T;
  weather?:
    | T
    | {
        temperatureC?: T;
        humidityPercent?: T;
        description?: T;
        fetchedAt?: T;
      };
  environment?: T;
  notes?: T;
  media?:
    | T
    | {
        setNumber?: T;
        type?: T;
        file?: T;
        label?: T;
        notes?: T;
        duration?: T;
        activeMovementSeconds?: T;
        capturedAt?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}